version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.swagger.core.v3:swagger-annotations
    versions:
    - 2.1.8
  - dependency-name: cn.hutool:hutool-all
    versions:
    - 5.5.9
    - 5.6.3
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.2
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.2
